# Generated by Django 5.2.10 on 2026-01-31 03:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("parsing", "Parsing Resume"),
                            ("parsed", "Resume Parsed"),
                            ("screening", "AI Screening"),
                            ("screened", "Screened"),
                            ("guardrail_check", "Guardrail Check"),
                            ("scoring", "Scoring"),
                            ("scored", "Scored"),
                            ("summarizing", "Summarizing"),
                            ("summarized", "Summarized"),
                            ("bias_audit", "Bias Audit"),
                            ("reviewed", "AI Review Complete"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "resume_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/%Y/%m/"),
                ),
                (
                    "resume_text",
                    models.TextField(
                        blank=True, help_text="Raw extracted text from resume"
                    ),
                ),
                (
                    "resume_redacted",
                    models.TextField(blank=True, help_text="PII-redacted resume text"),
                ),
                ("parsed_data", models.JSONField(blank=True, default=dict)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("experience_years", models.FloatField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, default=list)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("guardrail_results", models.JSONField(blank=True, default=dict)),
                ("guardrail_passed", models.BooleanField(null=True)),
                ("scoring_results", models.JSONField(blank=True, default=dict)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("summary_results", models.JSONField(blank=True, default=dict)),
                ("suggested_action", models.CharField(blank=True, max_length=50)),
                ("bias_audit_results", models.JSONField(blank=True, default=dict)),
                ("bias_flags", models.JSONField(blank=True, default=list)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("reviewer_decision", models.CharField(blank=True, max_length=50)),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BiasProbe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "probe_type",
                    models.CharField(
                        choices=[
                            ("name_swap", "Name Swap"),
                            ("proxy_flip", "Proxy Attribute Flip"),
                            ("adversarial", "Adversarial Injection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("scenario", models.CharField(max_length=200)),
                ("original_score", models.FloatField()),
                ("probe_score", models.FloatField()),
                ("delta", models.FloatField()),
                ("components", models.JSONField(default=dict)),
                ("explanation", models.TextField(blank=True)),
                ("flagged", models.BooleanField(default=False)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bias_probes",
                        to="core.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("parser", "Resume Parser"),
                            ("guardrail", "Guardrail Checker"),
                            ("scorer", "Scoring Agent"),
                            ("summarizer", "Summary Agent"),
                            ("bias_auditor", "Bias Auditor"),
                            ("orchestrator", "Orchestrator"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("llm_tokens_used", models.PositiveIntegerField(default=0)),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_executions",
                        to="core.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvaluationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "rubric_weights",
                    models.JSONField(
                        default=dict,
                        help_text="Component weights, e.g. {experience_ic: 0.25, education_rigor: 0.12, ...}",
                    ),
                ),
                (
                    "policies",
                    models.JSONField(
                        default=list, help_text="Responsible AI policies for scoring"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone Screen"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("panel", "Panel"),
                            ("final", "Final Round"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ai_suggested_questions", models.JSONField(blank=True, default=list)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="core.candidate",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "requirements",
                    models.TextField(help_text="Required skills and qualifications"),
                ),
                (
                    "nice_to_have",
                    models.TextField(blank=True, help_text="Preferred qualifications"),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("principal", "Principal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("min_experience_years", models.PositiveIntegerField(default=0)),
                ("max_experience_years", models.PositiveIntegerField(default=30)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("max_candidates", models.PositiveIntegerField(default=100)),
                (
                    "rubric_weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Scoring rubric component weights",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="job_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidates",
                to="core.jobposition",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("candidate_created", "Candidate Created"),
                            ("stage_changed", "Stage Changed"),
                            ("agent_completed", "Agent Completed"),
                            ("bias_flag", "Bias Flag Raised"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("decision_made", "Decision Made"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="core.candidate",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.jobposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
