# Generated by Django 5.2.10 on 2026-01-31 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="final_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="final_recommendation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="candidate",
            name="final_score",
            field=models.FloatField(
                blank=True, help_text="Combined AI + interview score", null=True
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Room, video link, phone number, etc.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="overall_rating",
            field=models.FloatField(
                blank=True, help_text="Average from all feedback scores", null=True
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="overall_recommendation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("candidate_created", "Candidate Created"),
                    ("stage_changed", "Stage Changed"),
                    ("agent_completed", "Agent Completed"),
                    ("bias_flag", "Bias Flag Raised"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_completed", "Interview Completed"),
                    ("feedback_submitted", "Feedback Submitted"),
                    ("offer_created", "Offer Created"),
                    ("offer_sent", "Offer Sent"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("decision_made", "Decision Made"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="stage",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("parsing", "Parsing Resume"),
                    ("parsed", "Resume Parsed"),
                    ("screening", "AI Screening"),
                    ("screened", "Screened"),
                    ("guardrail_check", "Guardrail Check"),
                    ("scoring", "Scoring"),
                    ("scored", "Scored"),
                    ("summarizing", "Summarizing"),
                    ("summarized", "Summarized"),
                    ("bias_audit", "Bias Audit"),
                    ("reviewed", "AI Review Complete"),
                    ("shortlisted", "Shortlisted"),
                    ("interview_setup", "Interview Setup"),
                    ("phone_screen", "Phone Screening"),
                    ("technical_interview", "Technical Interview"),
                    ("behavioral_interview", "Behavioral Interview"),
                    ("panel_interview", "Panel Interview"),
                    ("final_interview", "Final Interview"),
                    ("interview_complete", "Interviews Complete"),
                    ("final_evaluation", "Final Evaluation"),
                    ("approved_for_offer", "Approved for Offer"),
                    ("offer_drafting", "Drafting Offer"),
                    ("offer_approval", "Offer Approval"),
                    ("offer_extended", "Offer Extended"),
                    ("offer_negotiation", "Offer Negotiation"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("on_hold", "On Hold"),
                ],
                default="new",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes about the interview"
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("no_show", "No Show"),
                    ("rescheduled", "Rescheduled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HiringTeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("hiring_manager", "Hiring Manager"),
                            ("recruiter", "Recruiter"),
                            ("interviewer", "Interviewer"),
                            ("panel_member", "Panel Member"),
                            ("executive", "Executive"),
                        ],
                        default="interviewer",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "expertise_areas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Areas of expertise for interview matching",
                    ),
                ),
                ("max_interviews_per_week", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "calendar_link",
                    models.URLField(
                        blank=True, help_text="External calendar link for scheduling"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiring_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="InterviewRound",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round_type",
                    models.CharField(
                        choices=[
                            ("phone_screen", "Phone Screen"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("panel", "Panel"),
                            ("final", "Final Round"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Order in the interview sequence"
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "pass_threshold",
                    models.FloatField(
                        default=3.0, help_text="Minimum average rating to pass (1-5)"
                    ),
                ),
                (
                    "evaluation_criteria",
                    models.JSONField(
                        blank=True, default=list, help_text="Criteria for this round"
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_rounds",
                        to="core.jobposition",
                    ),
                ),
            ],
            options={
                "ordering": ["job_position", "order"],
                "unique_together": {("job_position", "order")},
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="interview_round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="core.interviewround",
            ),
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Drafting"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("sent", "Sent to Candidate"),
                            ("negotiating", "Negotiating"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="drafting",
                        max_length=20,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=12)),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                ("salary_period", models.CharField(default="annual", max_length=20)),
                (
                    "signing_bonus",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "equity_details",
                    models.TextField(blank=True, help_text="Stock options, RSUs, etc."),
                ),
                ("bonus_structure", models.TextField(blank=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                ("reporting_to", models.CharField(blank=True, max_length=200)),
                ("benefits_summary", models.TextField(blank=True)),
                ("offer_letter_text", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("negotiation_notes", models.TextField(blank=True)),
                ("counter_offer_details", models.JSONField(blank=True, default=dict)),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("candidate_response", models.TextField(blank=True)),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="core.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="core.jobposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "technical_score",
                    models.FloatField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "communication_score",
                    models.FloatField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "problem_solving_score",
                    models.FloatField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "culture_fit_score",
                    models.FloatField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "leadership_score",
                    models.FloatField(blank=True, help_text="1-5 scale", null=True),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        blank=True, help_text="1-5 overall rating", null=True
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("strong_hire", "Strong Hire"),
                            ("hire", "Hire"),
                            ("no_hire", "No Hire"),
                            ("strong_no_hire", "Strong No Hire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "detailed_scores",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional criteria scores"
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="core.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("interview", "interviewer")},
            },
        ),
        migrations.CreateModel(
            name="InterviewPanel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead Interviewer"),
                            ("member", "Panel Member"),
                            ("observer", "Observer"),
                            ("shadow", "Shadow (Learning)"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("confirmed", models.BooleanField(default=False)),
                ("declined", models.BooleanField(default=False)),
                ("decline_reason", models.TextField(blank=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panel_members",
                        to="core.interview",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["role"],
                "unique_together": {("interview", "interviewer")},
            },
        ),
        migrations.CreateModel(
            name="OfferApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1, help_text="Approval chain order"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("changes_requested", "Changes Requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offer_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="core.offer",
                    ),
                ),
            ],
            options={
                "ordering": ["offer", "order"],
                "unique_together": {("offer", "approver")},
            },
        ),
    ]
