# Generated by Django 5.2.10 on 2026-01-31 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_candidate_final_notes_candidate_final_recommendation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("hr", "HR Official"),
                            ("interviewer", "Interviewer"),
                            ("hiring_manager", "Hiring Manager"),
                            ("candidate", "Candidate"),
                            ("viewer", "Viewer (Read-Only)"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pics/%Y/%m/"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "title",
                    models.CharField(blank=True, help_text="Job title", max_length=200),
                ),
                ("department", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "mfa_secret",
                    models.CharField(
                        blank=True, help_text="TOTP secret key", max_length=64
                    ),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                (
                    "mfa_backup_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="One-time backup codes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked candidate record for candidate users",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="core.candidate",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
